#VMTurbo Classname
 - VirtualApplication
 - Application
 - Container
 - VirtualMachine
 - PhysicalMachine
 - Storage
 - DiskArray
 - StorageController
 - Switch
 - VPod
 - DPod
 - VirtualDatacenter
 - DataCenter